global_variables:
- current_time: 14.16.48
- current_date: 08-24-2022
- anomaly_report_filename: anomaly_report_08-24-2022_14.16.48.txt
- error_filename: error.log
- current_folder: C:\Users\ojelle.rogero\Desktop\Ojelle\gcp_validator\secret-sauce_oj\logs\08-24-2022\14.16.48
job_configs:
  - job_parameters: 
    - name: gcs_to_gcs
    - sources:
        - gs://staging-bucket-secret-sauce/pizza_v1.csv
        - gs://staging-bucket-secret-sauce/pizza_v2.csv
        - gs://staging-bucket-secret-sauce/student_data.csv
    - targets:
        - gs://staging-bucket-secret-sauce/pizza_v1.csv
        - gs://staging-bucket-secret-sauce/pizza_v2.csv
        - gs://staging-bucket-secret-sauce/student_data.csv
    - mode: default
  - job_parameters:
    - name: gcs_to_bq
    - sources:
        - gs://staging-bucket-secret-sauce/pizza_v1.csv
        - gs://staging-bucket-secret-sauce/pizza_v2.csv
        - gs://staging-bucket-secret-sauce/student_data.csv
    - targets:
        - agile-splicer-356706.dummy_data.pizza_v1
        - agile-splicer-356706.dummy_data.pizza_v2
        - agile-splicer-356706.dummy_data.student_data
    - mode: default
  - job_parameters:
    - name: bq_to_bq
    - sources:
        - agile-splicer-356706.dummy_data.pizza_v1
        - agile-splicer-356706.dummy_data.pizza_v2
        - agile-splicer-356706.dummy_data.student_data
    - targets:
        - agile-splicer-356706.dummy_data.pizza_v1
        - agile-splicer-356706.dummy_data.pizza_v2
        - agile-splicer-356706.dummy_data.student_data
    - mode: default
